/* Applicant journey & messages (2026-10-01, Samantha: "I need the full applicant experience to be mapped out with what
   messages they receive and attached somewhere in the hub pages so that our office admin know"). Built from the code as
   of 2026-10-01: every message an applicant / new hire gets, its exact wording, when it goes, what triggers it, and
   whether it shows in GoHighLevel Conversations. If a message is changed, update this list too. */
window.AP_JOURNEY_CHECKED = 'October 9, 2026 (checked by the journey check against the real messages; no em dashes)';
window.AP_JOURNEY = [
 {
  "stage": "applying",
  "order": 1,
  "name": "Send the application (office, after a phone call)",
  "trigger": "Staff type name/phone/email/position in Applicants and press Send.",
  "automatic": false,
  "button": "Applicants → '📨 Send the application' → Send",
  "timing": "Immediately; refused outside 8am–6pm Central (any day). Same phone/email not sent twice in 24h.",
  "channel": "text + email",
  "rule": "Text only if staff ticked 'They asked us to text it'; email whenever there is an address. Opt-out door on both. 'Reply STOP to opt out.' appended. Wording editable in Settings (ops_settings.applicant_invite_msg). FAILURE: GoHighLevel refusal is shown only in the Send pop-up (raw fetch, no Needs Attention card); opt-out holds raise a card.",
  "subject": "Your application for {position} at Caring Companions",
  "text": "Hi {first_name}, thanks for calling Caring Companions! Here's the application for {position}. It takes about 2 minutes: {link} Reply STOP to opt out.",
  "email_summary": "Hi {first}, thanks for calling about our {position} position. Here is the application. It takes about 2 minutes, and at the end you can pick a time for your in-person interview at our office. [Start the application] Questions? Call us at {office phone}.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 2,
  "name": "Applied, not booked: nudge 1 (regular roles)",
  "trigger": "the interview messages job automatic check (every 15 min) finds an application (status partial/new, under 14 days old, not declined) with no booked interview.",
  "automatic": true,
  "button": null,
  "timing": "2 hours after applying; only 8am–6pm Central (held until 8am otherwise).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts (their yes to texts); email to anyone with an address. Opt-out door per channel. No STOP wording in the text.",
  "subject": "Pick a time to come and meet us",
  "text": "Hi {first}, thanks for applying to Caring Companions. You are one step from an in-person interview at our office, and you can pick a time that suits you here: https://mo-care.com/apply?book={applicant_id}",
  "email_summary": "Same words as the text with the link clickable, plus the 'Where to come' block (office name, address, map link, note, entrance photo).",
  "shows_in_ghl": true,
  "failure_visible": true,
  "page": "https://mo-care.com/apply"
 },
 {
  "stage": "applying",
  "order": 3,
  "name": "Applied, not booked: nudge 1 (PRN CNA Team)",
  "trigger": "Same automatic check; PRN-track roles only, and only when the application cleared the screen (screen_grade 'qualified'). PRN applications that need a look get nothing automatically.",
  "automatic": true,
  "button": null,
  "timing": "10 minutes after they finish the application; 8am–6pm Central.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Choose your in-person interview time: PRN CNA Team",
  "text": "Hi {first}! Thanks for applying for Caring Companions' PRN CNA Team. Based on your Priority Application, we'd like to meet you in person. Choose an in-person interview time at our office here: https://mo-care.com/apply?book={applicant_id}",
  "email_summary": "Same words as the text plus the 'Where to come' block.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 4,
  "name": "Applied, not booked: nudge 2",
  "trigger": "Same automatic check; still no booking.",
  "automatic": true,
  "button": null,
  "timing": "48 hours after applying; 8am–6pm Central.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Pick a time to come and meet us",
  "text": "Hi {first}, we still have in-person interview times open at our office this week if you would like one: https://mo-care.com/apply?book={applicant_id} Or call us on {office phone} and we will book it with you.",
  "email_summary": "Same words as the text (no address block).",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 5,
  "name": "Applied, not booked: nudge 3 (last)",
  "trigger": "Same automatic check; still no booking.",
  "automatic": true,
  "button": null,
  "timing": "120 hours (5 days) after applying; 8am–6pm Central. At 7 days they are marked gave_up (no message).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "One last note from Caring Companions",
  "text": "Hi {first}, last note from us so we are not a nuisance. If you would still like to talk about caregiving work, pick a time here: https://mo-care.com/apply?book={applicant_id} or call {office phone}. We would be glad to hear from you.",
  "email_summary": "Same words as the text.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview booking",
  "order": 6,
  "name": "Interview booking confirmation",
  "trigger": "the interview messages job automatic check finds a booked interview with no a confirmation (booked on mo-care.com/apply, or by the office).",
  "automatic": true,
  "button": null,
  "timing": "Next 15-minute run after booking, 8am–6pm Central only (a 9pm booking is confirmed after 8am next day). If booked within 30h of the interview this also counts as the day-before reminder.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. No STOP wording.",
  "subject": "Your in-person interview: {day} at {time}",
  "text": "Hi {first}, your IN-PERSON interview with Caring Companions is booked for {Weekday, Month D} at {h:mm AM}. Please come to our office: {location}. {location note} This is not a phone interview, so we will not call you. Need to move or cancel it? https://mo-care.com/apply?book={applicant_id} or call {office phone}. Reply STOP to opt out.",
  "email_summary": "'Your in-person interview is booked for {day} at {time}.' + Where to come block (name, address, map, note, photo) + 'This is an in-person interview at our office, not a phone call, and it takes about 20 minutes (the calendar keeps a 30-minute slot). Need to move or cancel it? You can do that here, or call or text us.' + 'We are looking forward to meeting you.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview booking",
  "order": 7,
  "name": "Interview cancelled notice",
  "trigger": "A booking is cancelled (by the applicant on their manage link, or by the office) and they have not already rebooked.",
  "automatic": true,
  "button": null,
  "timing": "Next 15-minute run, 8am–6pm Central; looks back 7 days.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. A cancel followed by a rebook before the run sends nothing (the new confirmation covers it).",
  "subject": "Your interview on {day} is cancelled",
  "text": "Hi {first}, your interview with Caring Companions for {day} at {time} is cancelled, so there is nothing more to do. Want a different time? Pick one here: https://mo-care.com/apply?book={applicant_id} or call {office phone}.",
  "email_summary": "'Your interview for {day} at {time} is cancelled, nothing more to do on your side. If you would like a different time, pick one here whenever suits you, or call us on {phone}.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview reminders",
  "order": 8,
  "name": "Day-before reminder",
  "trigger": "the interview messages job automatic check: confirmed booking, not yet reminded, 2 to 30 hours away.",
  "automatic": true,
  "button": null,
  "timing": "Window opens 30h before; first run 8am–6pm Central inside that window. Skipped when the confirmation itself went inside 30h.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Tomorrow: your in-person interview at {time}",
  "text": "Hi {first}, reminder: your IN-PERSON interview is {Weekday, Month D} at {h:mm AM}. Please come to our office: {location}. {location note} This is not a phone interview, so we will not call you. Need to move or cancel it? {manage link} or call {office phone}. Reply STOP to opt out.",
  "email_summary": "'A reminder that your interview is tomorrow, {day} at {time}.' + Where to come block + 'It takes about {interview length from the Interviews settings, e.g. 45} minutes...' + move/cancel link.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview reminders",
  "order": 9,
  "name": "Hour-before reminder",
  "trigger": "the interview messages job automatic check: 1.5 hours before to 15 minutes after the start, not yet sent.",
  "automatic": true,
  "button": null,
  "timing": "Up to 90 minutes before; 8am–6pm Central (so an 8am interview gets it at 8:00).",
  "channel": "text only",
  "rule": "Text only with their yes to texts. Email-only applicants get NO hour-before reminder.",
  "subject": null,
  "text": "Hi {first}, your IN-PERSON interview with Caring Companions is at {time} today. Please come to our office: {location}. {location note} This is not a phone interview. See you shortly! Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "no-show",
  "order": 10,
  "name": "No-show message",
  "trigger": "Office presses 'Did not show' on the interview card (marks status noshow, closes the booking), or 'Send the no-show message' on the profile if it was held.",
  "automatic": false,
  "button": "Applicant interview card → 'Did not show'; profile → 'Send the no-show message' (only if not yet sent)",
  "timing": "Immediately, 8am–6pm Central (reactive). Outside hours the no-show is marked and the message waits for the profile button. Sent once (once only).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. Opt-out door. Her wording, fixed in code.",
  "subject": "Missed Interview – Caring Companions",
  "text": "Hi {first}, this is Caring Companions In-Home Senior Care. You were scheduled for an in-person interview with our office today and did not attend or contact us prior to your scheduled interview time.\n\nYour application has been marked as a No-Show, which means you will not be eligible to reapply or be considered for employment with Caring Companions in the future.\n\nWe understand that unexpected circumstances can happen. If there is a reasonable explanation for missing your interview, please call our office at 417-234-8494 as soon as possible so we can discuss the situation.\n\nThank you,\nCaring Companions In-Home Senior Care\n\nReply STOP to opt out.",
  "email_summary": "Same substance: marked as a No-Show, not eligible to reapply or be considered for future employment; if there is a reasonable explanation call 417-234-8494 and we will discuss whether the application may be reconsidered.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "no-show",
  "order": 11,
  "name": "Excuse no-show & rebook (no message)",
  "trigger": "Office presses '✅ Excuse no-show & rebook' after the applicant calls; reason required. Status goes back to 'reviewing'.",
  "automatic": false,
  "button": "Applicant profile → '✅ Excuse no-show & rebook'",
  "timing": "n/a",
  "channel": "none",
  "rule": "Sends nothing. The office books the new time; the normal booking confirmation then goes out from the interview messages job.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 12,
  "name": "Start link (sent with the job offer)",
  "trigger": "Office fills the Offer a job form after 'Hire, make the offer' and presses 'Save offer & send their start link'.",
  "automatic": false,
  "button": "Applicant interview card → '✅ Hire, make the offer' → 'Save offer & send their start link'",
  "timing": "Immediately when the office saves the offer. The text only goes 8am–6pm Central; the email any time.",
  "channel": "text + email",
  "rule": "Text only 8am–6pm Central, only if their application said yes to texts, and through the opt-out check; ends with \"Reply STOP to opt out.\" Anything not sent is listed on the offer screen and a refused message raises a \"Didn't go through\" card. Links sent before Oct 4 (which carried their details) keep working until Nov 3, then open an \"ask the office for a new link\" page.",
  "subject": "Getting you started at Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to bring you onto the team. One quick step before your offer letter goes out: https://cc.mo-care.com/start.html?o=..&e=..&t=.. (private: no name, phone or email in it) It takes about two minutes and lets us start your reference checks today.",
  "email_summary": "'We would love to bring you onto the team. Your official offer letter and new-hire paperwork are on their way... Reference checks are the slowest part of hiring, so we start them the same day. This takes about two minutes: [Get started]' + office number.",
  "shows_in_ghl": true,
  "failure_visible": true,
  "page": "https://cc.mo-care.com/start.html?preview=1"
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13,
  "name": "Start link resend (from staff's own phone/email)",
  "trigger": "Office presses 'Start link' on the hiring pipeline person row, then '💬 Text it' or '✉️ Email it'.",
  "automatic": false,
  "button": "Hiring pipeline row → 'Start link' → '💬 Text it' / '✉️ Email it' / '📋 Copy link'",
  "timing": "Whenever pressed.",
  "channel": "text or email from the staff member's own device",
  "rule": "Opens sms:/mailto: on the staff member's phone or computer. No opt-out check, no record. The link is the same private link (no name, phone or email in it).",
  "subject": "Getting you started at Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to bring you onto the team. One quick step before your offer letter goes out: {private start link} It takes about two minutes and lets us start your reference checks today.",
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.1,
  "name": "Offer letter link (NEW onboarding path, Slice 1c)",
  "trigger": "Office presses 'Save offer & send their start link' on an offer dated on or after the switch date (ops_settings.onboarding_switch_date, Owners Hub Admin). Until that date is set nobody is on the new path.",
  "automatic": true,
  "button": "Offer a job form → 'Save offer & send their start link' (the server decides the path; the browser never does)",
  "timing": "Immediately when the offer is saved. The text only 8am to 6pm Central (after hours it is HELD, not failed, and goes at 8am); the email at once. PRACTICE while the Admin switch 'Offer letter link goes out (new path)' is off: recorded, nothing sent.",
  "channel": "text + email",
  "rule": "Text only 8am to 6pm Central, only if their application said yes to texts, and through the opt-out check; ends with \"Reply STOP to opt out.\" The link carries only the offer's record number and a code, dies with the offer (seven business days, 5pm Central), and opens the offer letter then the position description to read and sign on the phone. A second open offer for the same phone or email within 60 days is refused on both paths (re-offer needs an authorized person and a typed reason). Each send, hold, refusal, withdrawal and resend is a row on the append-only offer_events trail; a refused channel raises a Didn't go through card.",
  "subject": "Your offer from Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to have you on the team. Your offer is ready to read and sign on your phone, it takes about two minutes: https://cc.mo-care.com/offer.html?o=...&e=...&t=... If anything looks off, call or text the office at (417) 234-8494. Reply STOP to opt out.",
  "email_summary": "Hi {first}, We would love to have you on the team. Your offer is ready to read and sign on your phone, it takes about two minutes. Position / Pay rate / Hours. [Sign my offer] Or paste this into your browser: {link}. If anything looks off, call or text the office at (417) 234-8494. The Caring Companions team",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.2,
  "name": "Offer letter link sent again (Resend on the Open offers card, new path)",
  "trigger": "Office presses 'Resend' on the offer's card (Recruit & Onboard → Offers → Open offers). Refused once both documents are signed, or when the offer is withdrawn or declined.",
  "automatic": false,
  "button": "Offers → Open offers → the card's 'Resend'",
  "timing": "Immediately; same hours rule as the first send. An expired offer gets a fresh expiry from the company calendar and a fresh link; the old link died with the old expiry.",
  "channel": "text + email",
  "rule": "Same wording and gates as the first send; a 'resent' row on the audit trail. In practice mode nothing is sent.",
  "subject": "Your offer from Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to have you on the team. Your offer is ready to read and sign on your phone, it takes about two minutes: https://cc.mo-care.com/offer.html?o=...&e=...&t=... If anything looks off, call or text the office at (417) 234-8494. Reply STOP to opt out.",
  "email_summary": "The same email as the first send.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.3,
  "name": "Step 1 link (sends itself after both signatures, NEW onboarding path, Slice 1d)",
  "trigger": "The applicant signs the offer letter and the position description on their phone (the signing page). The Training Platform reads the saved record and sends; the signing page itself never sends anything.",
  "automatic": true,
  "button": null,
  "timing": "Within a minute of the second signature (the page kicks the sender; a scheduled run every 15 minutes, 8am to 6pm Central, catches anything the kick missed). The text only 8am to 6pm Central (held until 8am otherwise); the email at once. PRACTICE while the Admin switch 'Step 1 sends itself after the signature (new path)' is off: recorded, nothing sent.",
  "channel": "text + email",
  "rule": "Sent once: the stamp is written when the first attempt goes, so a second trigger sends nothing. A channel that fails is retried by the Hub up to three times over the following hours, never after 6pm, never twice within an hour, never a channel that already went; after the third failure, or at once when both channels fail, a Needs Attention card is raised and the Hub stops; Resend Step 1 by a person is the only further send. Yes-to-texts and the opt-out check on every try; ends with \"Reply STOP to opt out.\" Every send, retry and give-up is a row on the append-only offer_events trail. In Slice 1 the link is the existing start form as a stand-in; Slice 2 points it at the nine Step 1 screens.",
  "subject": "Step 1: your new-hire paperwork",
  "text": "Thank you, {first}, your offer is signed and we are so glad to have you. Next is Step 1, your new-hire paperwork, done right on your phone: https://cc.mo-care.com/start.html?o=...&e=...&t=... It takes about 15 minutes and you can stop and pick it back up any time. Questions? Call or text the office at (417) 234-8494. Reply STOP to opt out.",
  "email_summary": "Thank you, {first}, your offer is signed and we are so glad to have you. Next is Step 1, your new-hire paperwork, done right on your phone. [Open Step 1] It takes about 15 minutes, saves as you go, and you can stop and pick it back up any time. Signed copies come back to you when it is done. Questions? Call or text the office at (417) 234-8494. The Caring Companions team",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.35,
  "name": "Step 1 reminders, day 2 and day 4 (NEW onboarding path, Slice 2d)",
  "trigger": "The scheduled run (every 15 minutes) finds a new-path offer whose Step 1 link went 2 days, and again 4 days, ago and whose Step 1 is not done (the days are set on the Owners Hub Admin page, default 2 and 4).",
  "automatic": true,
  "button": null,
  "timing": "Monday to Saturday, 9am to 6pm Central; one stamp per reminder, so each goes at most once; never once Step 1 is done, or the offer is withdrawn or declined.",
  "channel": "text + email",
  "rule": "Practice while the Admin switch step1_auto_live is off: recorded on the trail (step1_reminder), nothing sent. Live: a fresh private Step 1 link each time; the opt-out door, Do Not Disturb and the text-consent check apply; STOP on every text.",
  "subject": "Your Step 1 paperwork is waiting for you",
  "text": "Hi {first}, a friendly reminder from Caring Companions: your Step 1 new-hire paperwork is waiting for you: https://cc.mo-care.com/step1.html?o=...&e=...&t=... It picks up right where you left off and takes about 15 minutes. Questions? Call or text the office at (417) 234-8494.",
  "email_summary": "Hi {first}, a friendly reminder from Caring Companions: your Step 1 new-hire paperwork is waiting for you. [Pick up Step 1] It picks up right where you left off and takes about 15 minutes. Questions? Call or text the office at (417) 234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.36,
  "name": "Step 1 receipt (all seven forms signed, NEW onboarding path, Slice 2d)",
  "trigger": "The Hub's Step 1 server stamps step1_done_at at the seventh signature; the scheduled run sees the stamp and sends the receipt once (step1_receipt_at).",
  "automatic": true,
  "button": null,
  "timing": "The next scheduled run after the last signature (every 15 minutes, 8am to 6pm Central).",
  "channel": "text + email",
  "rule": "Once per offer. Practice while the Admin switch step1_auto_live is off: recorded on the trail (step1_receipt), nothing sent. The signed copies themselves live on the Step 1 page behind the private link; nothing is attached.",
  "subject": "Your Step 1 paperwork is complete",
  "text": "Thank you, {first}, your Step 1 paperwork is complete. Your signed copies are on your Step 1 page: https://cc.mo-care.com/step1.html?o=...&e=...&t=... Next the office orders your background checks and contacts your references; then you will hear from us about Step 2, your payroll paperwork in Viventium, and your welcome call. Questions? Call or text the office at (417) 234-8494.",
  "email_summary": "Thank you, {first}, your Step 1 paperwork is complete. [Your signed copies] Next the office orders your background checks and contacts your references; then you will hear from us about Step 2, your payroll paperwork in Viventium, and your welcome call. Questions? Call or text the office at (417) 234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13.4,
  "name": "Offer reminders, day 2 and day 5 (NEW onboarding path, Slice 1e)",
  "trigger": "The scheduled run (every 15 minutes) finds an offer on the new path that is not signed, declined, withdrawn or expired, 2 days and again 5 days after it was sent (the days are set on the Owners Hub Admin page, Reminder days and deadlines).",
  "automatic": true,
  "button": null,
  "timing": "On each reminder day, the first run inside Monday to Saturday 9am to 6pm Central. One stamp per reminder, so each goes once. Stopped by a signature, a decline or a withdrawal. PRACTICE while the Admin switch 'Offer reminders go out (new path)' is off: recorded and stamped, nothing sent.",
  "channel": "text + email",
  "rule": "Yes-to-texts and the opt-out check on every send; ends with \"Reply STOP to opt out.\" The link is the same private offer link, which dies with the offer. Day 7 unsigned: no third message; a Needs Attention card \"Offer not signed: call {name}\" is raised once (practice or not). An offer past its expiry is marked expired, raises that card if it has not been raised, and Resend from the card makes a fresh link. A held offer text (sent after 6pm) goes at the first run after 8am. Every reminder, card and expiry is a row on the append-only offer_events trail; a refused channel raises a Didn't go through card.",
  "subject": "Your offer from Caring Companions is waiting for your signature",
  "text": "Hi {first}, your offer from Caring Companions is still waiting for your signature. It takes about two minutes: https://cc.mo-care.com/offer.html?o=...&e=...&t=... Questions? Call or text (417) 234-8494. Reply STOP to opt out.",
  "email_summary": "Hi {first}, your offer from Caring Companions is still waiting for your signature. It takes about two minutes. [Sign my offer] Or paste this into your browser: {link}. Questions? Call or text (417) 234-8494. The Caring Companions team",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 14,
  "name": "Not hiring message",
  "trigger": "Office presses 'Not hiring' on the interview card, or 'Not moving forward' on the applicant, then OK on the message shown. Not offered to anyone already marked Offer or Hired (a background check issue gets the background review's notice instead).",
  "automatic": false,
  "button": "Applicant → 'Not hiring' / 'Not moving forward' → OK on the message",
  "timing": "When OK is pressed, 8am to 6pm Central.",
  "channel": "text (or email if they said no to texts)",
  "rule": "Never automatic: after the office marks them, the Hub shows the exact message with OK (send) or Cancel (send nothing). One message per decision. A text needs their yes to texts on the application; without it the email goes instead, if we have one. Texts and emails go 8am to 6pm Central only and texts end with \"Reply STOP to opt out.\" Outside those hours it waits and their profile shows \"Send the message\" / \"Don't send it\". The reason the office wrote is never sent. A refused message raises a Needs Attention card.",
  "subject": "Your application with Caring Companions",
  "text": "Hi {first}, thank you for applying with Caring Companions and for your time. We've decided not to move forward right now. We wish you the very best. Reply STOP to opt out.",
  "email_summary": "Same words, signed Caring Companions In-Home Senior Care, 417-234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 14.5,
  "name": "Candidate pool message",
  "trigger": "Office presses '🗂 Candidate pool' (interview card or applicant list), then OK on the message shown. Not sent when only editing what a pool member is waiting for, or when the whole Inactive list is moved into the pool. Not offered to anyone already marked Offer or Hired.",
  "automatic": false,
  "button": "Applicant → '🗂 Candidate pool' → OK on the message",
  "timing": "When OK is pressed, 8am to 6pm Central.",
  "channel": "text (or email if they said no to texts)",
  "rule": "Never automatic: after the office marks them, the Hub shows the exact message with OK (send) or Cancel (send nothing). One message per decision. A text needs their yes to texts on the application; without it the email goes instead, if we have one. Texts and emails go 8am to 6pm Central only and texts end with \"Reply STOP to opt out.\" Outside those hours it waits and their profile shows \"Send the message\" / \"Don't send it\". The reason the office wrote is never sent. A refused message raises a Needs Attention card.",
  "subject": "Your application with Caring Companions",
  "text": "Hi {first}, thank you for applying with Caring Companions. We don't have the right opening for you today, but we've kept your application and will reach out when one comes up. Reply STOP to opt out.",
  "email_summary": "Same words, signed Caring Companions In-Home Senior Care, 417-234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 15,
  "name": "Not moving forward courtesy text (legacy Onboarding board)",
  "trigger": "Office presses 🚫 on an Onboarding board candidate, picks a reason (not 'withdrew'), then OKs the courtesy-text prompt.",
  "automatic": false,
  "button": "Onboarding board → 🚫 (Not moving forward) → confirm 'Send a courtesy text'",
  "timing": "Immediately when pressed, 8am–6pm Central.",
  "channel": "text only",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" Otherwise nothing is sent and the office is told why. Never for the reason \"Background check issue\": that gets the background review's final notice instead, so nobody gets both.",
  "subject": null,
  "text": "Hi {first}, thank you for your interest in joining Caring Companions. After careful review, we won't be moving forward with your application at this time. We appreciate the time you invested and wish you all the best. Caring Companions (417) 234-8494",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 16,
  "name": "Tell past applicants about an opening",
  "trigger": "Office picks a group in 'Find someone for a case', writes the message, presses 'Send it'.",
  "automatic": false,
  "button": "Applicants → '🎯 Find someone for a case' → 'Send it'",
  "timing": "Weekdays 8am–6pm Central only (proactive). Nobody twice in 30 days.",
  "channel": "text + email",
  "rule": "Staff-written message. Text only with their yes to texts; email to anyone with an address. Skips declined/hired/offer and anyone with a booked interview. Does NOT skip no-shows.",
  "subject": "A new opening at Caring Companions",
  "text": "Hi {first}, {staff message} https://mo-care.com/apply?book={applicant_id} Reply STOP to hear no more from us.",
  "email_summary": "'Hi {first}, {staff message}' + [Pick an interview time] button + 'You applied with us before, which is why we thought of you. If you would rather we did not get in touch again, just reply and say so.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 17,
  "name": "Reference nudge to the applicant",
  "trigger": "reference-chase (weekday automatic check + a poke when reference rows are created): a reference has been silent 5 days.",
  "automatic": true,
  "button": null,
  "timing": "5 days after the reference was first asked; weekdays 8am–6pm (automatic check 9:30/10:30am Central). Once per reference.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts on the apply form (by applicant id, or every application with that number said yes). Opt-out door. 'Reply STOP to opt out.' included.",
  "subject": "We cannot reach {reference name}",
  "text": "Hi {first}, Caring Companions here. We have not been able to reach {reference name} for your reference, and we need it before you can start. Give them a nudge if you can. Or if you have a better number or email for them, or want to use someone else, do it here: https://cc.mo-care.com/fix-reference.html?r=..&cid=..&n=.. Reply STOP to opt out.",
  "email_summary": "'We have not been able to reach {ref} for your reference, and it is we need it before you can start with us. Could you give them a nudge? ... Or if you have a better number or email, or would rather use someone else, tell us here: [Give us a different contact]'",
  "shows_in_ghl": true,
  "failure_visible": true,
  "page": "https://cc.mo-care.com/fix-reference.html?r=preview&cid=0&n=Denise%20Hollan"
 },
 {
  "stage": "references",
  "order": 18,
  "name": "To the reference (not the applicant): first ask",
  "trigger": "reference-chase: a reference row with an email and no sent_at.",
  "automatic": true,
  "button": null,
  "timing": "As soon as the rows are created (Hub poke) or the next weekday 9:30am run; weekdays 8am–6pm.",
  "channel": "email only",
  "rule": "References are never texted automatically. No email = office call card.",
  "subject": "A quick reference for {candidate name}",
  "text": null,
  "email_summary": "'{candidate} listed you as a reference for a caregiving job with us... a few quick questions, no wrong answers. An honest middling answer helps us more than a glowing one.' [Answer a few quick questions]",
  "shows_in_ghl": true,
  "failure_visible": true,
  "page": "https://cc.mo-care.com/reference.html?r=preview&c=Jordan%20Ellis&n=Denise%20Hollan&rel=Charge%20nurse"
 },
 {
  "stage": "references",
  "order": 19,
  "name": "To the reference (not the applicant): one reminder",
  "trigger": "reference-chase: reference silent 2 days.",
  "automatic": true,
  "button": null,
  "timing": "2 days after the first ask; weekdays 8am–6pm. Once.",
  "channel": "email only",
  "rule": "Email only.",
  "subject": "A quick reference for {candidate name}",
  "text": null,
  "email_summary": "'A gentle nudge. {candidate} cannot start with us until their references are in, and we still need yours.' [Answer a few quick questions]",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 20,
  "name": "To the reference (not the applicant): office sends the form",
  "trigger": "Office presses email or text on a reference in Background & References (text only after recording 'said OK to a text, by phone').",
  "automatic": false,
  "button": "Background & References → reference row → email the form / text the form",
  "timing": "Immediately, 8am–6pm Central.",
  "channel": "email or text",
  "rule": "Text needs recorded verbal OK. Raw fetch: a GoHighLevel refusal shows only to the person who pressed (no card).",
  "subject": "A quick reference for {candidate name}",
  "text": "Hi {ref first}, this is Caring Companions In-Home Senior Care. Thanks for saying we could text you. {candidate} listed you as a reference. A few quick questions, about two minutes: {link} Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "background checks",
  "order": 20.5,
  "name": "Something came up (background check, step 1)",
  "trigger": "A check is recorded as flagged (OIG FLAGGED; EDL, FCSR or fingerprints Issues Found). The office opens the background review and presses OK on the message. A finding is never an automatic not hired: the office picks the review result.",
  "automatic": false,
  "button": "Background & References → 🛡 Something came up (or 🛡 Background review) → OK",
  "timing": "When OK is pressed. Sets the Applicant response due date: 5 business days (Monday to Friday).",
  "channel": "text + email",
  "rule": "Only after an office person presses OK on the exact words shown; Cancel sends nothing. Our own direct checks only (FCSR, EDL, OIG, fingerprints). The text never names the check; the email names it, never any detail. Texts 8am to 6pm Central, only with their yes to texts, ending with \"Reply STOP to opt out.\"; the email goes when there is one; outside those hours nothing goes. Every step is recorded on the review (bg_reviews) with who and when. Instead of the message the office can record \"told them by phone or in person\".",
  "subject": "About your background screening",
  "text": "Hi {first}, this is Caring Companions. Something came up in your background screening that we'd like to go over with you before we continue your application. Please call us at (417) 234-8494 within 5 business days. Reply STOP to opt out.",
  "email_summary": "Names the check (Missouri Family Care Safety Registry screening / Missouri Employee Disqualification List check / federal OIG exclusion list check / fingerprint background check), says no decision has been made, asks them to call by the due date, and invites them to tell us anything, including a Good Cause Waiver. No details of the finding.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "background checks",
  "order": 20.6,
  "name": "Background final notice (step 2)",
  "trigger": "The office presses 'Send the final notice' on the background review, then OK. Only after step 1 (or told by phone), a review result of Waiver needed, Can't be employed, or No waiver needed with a written reason, the response due date passed or 'Spoke with them' recorded, and not while waiting on a Good Cause Waiver. They are then marked Not hired (Background check issue).",
  "automatic": false,
  "button": "Background review → Send the final notice → OK",
  "timing": "When OK is pressed.",
  "channel": "text + email",
  "rule": "Only after an office person presses OK on the exact words shown; Cancel sends nothing. Our own direct checks only (FCSR, EDL, OIG, fingerprints). The text never names the check; the email names it, never any detail. Texts 8am to 6pm Central, only with their yes to texts, ending with \"Reply STOP to opt out.\"; the email goes when there is one; outside those hours nothing goes. Every step is recorded on the review (bg_reviews) with who and when. Cleared (not them, an error corrected, no waiver needed, or a waiver approved with the letter) sends nothing.",
  "subject": "Your application with Caring Companions",
  "text": "Hi {first}, thank you for your time. After reviewing your background screening, we're not able to move forward with your application for a caregiving position. We've emailed you more information. Reply STOP to opt out.",
  "email_summary": "One of four: FCSR or fingerprints needing a waiver (Missouri rules; how to apply for a Good Cause Waiver, 1-866-422-6872; welcome to reapply if granted) · our decision (no rules claim) · EDL (Missouri law; contact DHSS if in error) · OIG (federal list; reinstatement information at oig.hhs.gov/exclusions).",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "start paperwork",
  "order": 21,
  "name": "Welcome / what happens next (Viventium)",
  "trigger": "Office marks the offer 'entered in Viventium' (auto-sends), or presses '💬 Send welcome text + email' to retry.",
  "automatic": false,
  "button": "Hiring pipeline row → '☑ Viventium' / offer ladder 'Mark entered in Viventium'; retry '💬 Send welcome text + email'",
  "timing": "When Staffing marks them entered in Viventium. The text only goes 8am–6pm Central; the email any time. Once.",
  "channel": "text + email",
  "rule": "Same text rules as the start link (hours, their yes to texts, opt-out check, STOP line). Anything not sent is shown to the office.",
  "subject": "Welcome to Caring Companions, here’s what happens next",
  "text": "Hi {first}! Congratulations, and welcome to Caring Companions! 🎉\nWe're excited to begin the onboarding process with you.\n\nYour next step is to watch your email for a message from Viventium, our secure onboarding system. It will contain your official job offer and the first portion of your onboarding paperwork.\n\nPlease complete it as soon as possible. This paperwork gives us permission to begin your background check and contact your professional references.\n\nOnce your background check and references are complete, we'll text you to book a quick 15-minute welcome video call. After that, you'll do your paid training from home on your phone or computer.\n\n📞 Please save our office number: (417) 234-8494. This is our main office number and the one you'll use to call or text us if you have any questions.\n\nWelcome to the Caring Companions team!",
  "email_summary": "Congratulations + Step 1 complete Viventium paperwork (official offer + first paperwork; authorizes background check and references) / Step 2 background and reference checks / Step 3 your 15-minute welcome video call (once checks and references are complete we send Viventium Step 2 and a link to book it; join from phone or computer) / Step 4 paid training from home (after the call, a private link by text to the paid orientation and Alzheimer's and dementia training, in pieces if they like) / save office number (417) 234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "start paperwork",
  "order": 22,
  "name": "Viventium offer letter + paperwork reminders (external)",
  "trigger": "Office enters the hire in Viventium.",
  "automatic": true,
  "button": null,
  "timing": "Viventium's own schedule (code notes it reminds every 2 days).",
  "channel": "email (Viventium)",
  "rule": "Outside the Hub. Wording not in our code.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.1,
  "name": "Welcome call invite",
  "trigger": "Office presses 'Invite to welcome call' (after references + background clear and Viventium Step 2 is done), reviews the message, confirms.",
  "automatic": false,
  "button": "Ready for Orientation row / Background tab → 'Invite to welcome call'",
  "timing": "Immediately when pressed.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "Book your welcome call with Caring Companions",
  "text": "Hi {first}, great news from Caring Companions! Your background check and references are complete. Next step: a quick 15-minute welcome video call where we show you how to complete your paid orientation from your phone or computer. Book a time here: https://cc.mo-care.com/welcome.html?w=.. Reply STOP to opt out.",
  "email_summary": "Background and references complete; a 15-minute welcome video call where we show them how to complete their paid orientation from their phone or computer (button: Book my welcome call); we also check ID for paperwork, set up the AxisCare app and go over the caregiver profile; have the original ID documents uploaded in Viventium; join from the phone, no app needed.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.2,
  "name": "Welcome call booked (confirmation)",
  "trigger": "They pick a time on the welcome call page.",
  "automatic": true,
  "button": null,
  "timing": "Shortly after booking (the next automatic check).",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "Your welcome call: {day} at {time}",
  "text": "Hi {first}, your welcome video call with Caring Companions is booked for {day} at {time}. At that time, tap this link to join from your phone: https://meet.google.com/yqj-nzuo-tgp Please have the original ID documents you uploaded in Viventium with you. Need a different time? https://cc.mo-care.com/welcome.html?w=.. Reply STOP to opt out.",
  "email_summary": "Booked day and time, 'Join the video call' button, bring original ID documents, link to pick a new time, office phone.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.3,
  "name": "Welcome call day-before reminder",
  "trigger": "Automatic, the day before a booked call.",
  "automatic": true,
  "button": null,
  "timing": "Up to 30 hours before the call. Skipped if they booked within 30 hours (the confirmation covers it).",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "Tomorrow: your welcome call at {time}",
  "text": "Hi {first}, reminder: your welcome video call is {day} at {time}. At that time, tap this link to join from your phone: https://meet.google.com/yqj-nzuo-tgp Please have the original ID documents you uploaded in Viventium with you. Need a different time? https://cc.mo-care.com/welcome.html?w=.. Reply STOP to opt out.",
  "email_summary": "Same as the confirmation, worded as a reminder.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.4,
  "name": "Welcome call hour-before text",
  "trigger": "Automatic, about an hour before a booked call.",
  "automatic": true,
  "button": null,
  "timing": "About 1 hour before. Text only.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": null,
  "text": "Hi {first}, your welcome video call with Caring Companions is at {time} today. At that time, tap here to join: https://meet.google.com/yqj-nzuo-tgp Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.5,
  "name": "Welcome call moved: Step 2 not done",
  "trigger": "Office presses 'Reschedule: Step 2 not done'.",
  "automatic": false,
  "button": "Orientations → Welcome calls → 'Reschedule: Step 2 not done'",
  "timing": "Immediately when pressed.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "Please finish your Viventium Step 2, then pick a new time",
  "text": "Hi {first}, your Viventium Step 2 paperwork needs to be finished before your welcome call, so we have moved your {day} at {time} call. Please finish Step 2 (look for the email from Viventium), then pick a new time here: https://cc.mo-care.com/welcome.html?w=.. Questions? Call 417-234-8494. Reply STOP to opt out.",
  "email_summary": "Step 2 must be finished first; look for the Viventium email; 'Pick a new time' button.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.6,
  "name": "Welcome call moved by the office",
  "trigger": "Office presses 'Reschedule (other)'.",
  "automatic": false,
  "button": "Orientations → Welcome calls → 'Reschedule (other)'",
  "timing": "Immediately when pressed.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "Please pick a new time for your welcome call",
  "text": "Hi {first}, we need to move your {day} at {time} welcome call with Caring Companions. Please pick a new time here: https://cc.mo-care.com/welcome.html?w=.. Sorry for the change! Questions? Call 417-234-8494. Reply STOP to opt out.",
  "email_summary": "We need to move the call, sorry; 'Pick a new time' button.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.7,
  "name": "Missed welcome call",
  "trigger": "Office presses 'Did not show'.",
  "automatic": false,
  "button": "Orientations → Welcome calls → 'Did not show'",
  "timing": "Immediately when pressed.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "We missed you at your welcome call",
  "text": "Hi {first}, we missed you at your welcome video call with Caring Companions. No problem, pick a new time here: https://cc.mo-care.com/welcome.html?w=.. Questions? Call 417-234-8494. Reply STOP to opt out.",
  "email_summary": "We missed you, no problem; 'Pick a new time' button.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.8,
  "name": "Call them now (an opening right now)",
  "trigger": "Office presses 'Call them now', e.g. when an interview no-shows and the room is free.",
  "automatic": false,
  "button": "Orientations → Welcome calls → 'Call them now'",
  "timing": "Immediately when pressed. Refused if another welcome call is in the next 15 minutes.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card.",
  "subject": "We have an opening right now for your welcome call",
  "text": "Hi {first}, it's Caring Companions. We have an opening right now for your 15-minute welcome video call. If you can join in the next 10 minutes, tap here: https://meet.google.com/yqj-nzuo-tgp Please have your original ID documents with you. If now does not work, no problem, pick a time here: https://cc.mo-care.com/welcome.html?w=.. Reply STOP to opt out.",
  "email_summary": "Opening right now; 'Join the video call now' button; bring original ID documents; if they already have a time booked, it stays.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "welcome call (remote orientation)",
  "order": 22.9,
  "name": "Caregiver profile photo link",
  "trigger": "On the welcome call, after reading their drafted profile to them, the office presses '🪪 Caregiver profile' → 'Send photo link', reviews the message, confirms.",
  "automatic": false,
  "button": "Welcome call card / Ready for Orientation row / Background tab / the employee's page → '🪪 Caregiver profile' → 'Send photo link'",
  "timing": "Immediately when pressed. Can be sent again until the profile is published (then their link is locked).",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card. The link is their own (personal token), not the public card link. Sending ticks 'Photo link sent' on their open welcome call.",
  "subject": "Add your photo to your Caring Companions profile",
  "text": "Hi {first}, it's Caring Companions! Please finish your caregiver profile here: https://cc.mo-care.com/caregiver-profile.html?t=.. Add a friendly photo of yourself (we need this one) and, if you like, a short hello video. Then check the words we wrote about you. Families see your profile before you visit, so they know who is coming. Reply STOP to opt out.",
  "email_summary": "Before your first visit the family sees a short profile of you; 1. add a friendly photo (needed; a phone selfie in good light, shoulders up), 2. if you like, a short hello video of about 30 seconds, 3. read the words we wrote and change anything that does not sound like you; 'Finish my profile' button; the link is just for you; office phone.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 22.95,
  "name": "Orientation link (training welcome)",
  "trigger": "Office presses 'Welcome call done – send orientation link' at the end of the welcome call (or 'Send orientation link' on their row under Done recently). The Training Platform finds them in AxisCare by phone number or email (never by name; exactly one active caregiver In Training), assigns their courses, links their offer and sends it. The Training Platform's 9am run sends the same message to anyone In Training who has not had it yet.",
  "automatic": false,
  "button": "Orientations → Welcome calls → 'Welcome call done – send orientation link'; to retry: Done recently → 'Send orientation link'",
  "timing": "Right after the welcome call, 8am–6pm Central. After 6pm (or before 8am) the whole welcome is held and goes with the 9am run. Never sent twice.",
  "channel": "text + email",
  "rule": "Only once they are an active caregiver In Training in AxisCare (the office hires them and sets In Training during the welcome call). Not found, or more than one match: nothing is sent, the office is told to set In Training in AxisCare and press Send orientation link, and a card goes on Needs Attention. Text only if their application did not say no to texts (if it did, the email still goes); 8am–6pm Central; ends with \"Reply STOP to opt out.\" Opt-out check on both. Anything that stops it (Do Not Disturb, no phone or email, an opt-out list that could not be checked, a GoHighLevel refusal) raises a \"Didn't go through\" card, once per person.",
  "subject": "Welcome to Caring Companions, your orientation is ready",
  "text": "Hi {first}, welcome to Caring Companions! Your orientation is ready. Start any time on your phone or computer:\nhttps://training.mo-care.com/#/me/{token}\nIt's 2 hours of orientation plus 4 hours of dementia care training, and you can do it in pieces. This private link is just for you, no login needed. Questions? Call or text the office at (417) 234-8494. Caring Companions.\nReply STOP to opt out.",
  "email_summary": "Welcome, your orientation is ready on your phone, tablet or computer; private link, no login needed; [Start my orientation] (and the link to paste); before your first client visit complete Agency Orientation (2 hours) and Alzheimer's & Dementia Care (4 hours), in pieces if you like, progress saves; once your training is done and your caregiver profile is published we will let you know you are cleared to work; office (417) 234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 23,
  "name": "Orientation invite (pick your date)",
  "trigger": "Office presses '📅 Invite' (or '📅 Re-send') on a candidate who is 'Ready for Orientation', reviews the text, confirms.",
  "automatic": false,
  "button": "Onboarding board (Ready for Orientation) → '📅 Invite' / '📅 Re-send'",
  "timing": "Immediately when pressed, 8am–6pm Central.",
  "channel": "text only",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" Otherwise nothing is sent and the office is told why. The link opens the booking page on sc.mo-care.com. Orientation links sent before Oct 4 (which carried their details) keep working until Nov 3, then open an \"ask the office for a new link\" page.",
  "subject": null,
  "text": "Hi {first}! Congratulations, you've been cleared to join Caring Companions! 🎉 Please choose your orientation date here: https://sc.mo-care.com/orientation-booking.html?sessions=..&c=..&e=..&t=.. (private: no name, phone or email in it)\n\nQuestions? Call/text (417) 234-8494. We can't wait to meet you!",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 24,
  "name": "Orientation booking confirmation",
  "trigger": "Candidate picks a date on orientation-booking.html; the page asks send-candidate-message for the fixed confirmation (real booking in last 15 min, upcoming session). Or (from 2026-10-08) the office sets the date and time itself in the Hub's office orientation window and presses 'Book and text them the details': the same words go from the Hub as an office text.",
  "automatic": true,
  "button": "Orientations tab (Ready for Orientation) → '📅 In the office instead' → 'Book and text them the details' (office-set date). 'Book only' texts nothing.",
  "timing": "Instantly, any hour, when they booked it themselves (one per phone per 24h). When the office sets the date: immediately when pressed, 8am–6pm Central only.",
  "channel": "text only",
  "rule": "Goes right away, at any hour (they just booked it themselves). One per phone per 24 hours. Through the opt-out check; ends with \"Reply STOP to opt out.\" No check of their yes to texts (they asked for it by booking). A refused text raises a Needs Attention card. When the office sets the date and presses Book and text them, it follows the office text rules instead: 8am to 6pm Central, only with their yes to texts, and the person who pressed it is told if nothing went.",
  "subject": null,
  "text": "You're all set, {first}! 🎉 Your Caring Companions orientation is {Weekday, Month D, YYYY} at {h:mm AM}. Location: 1331 N Stewart Ave Ste B, Springfield MO 65802. [or: This is a video call: {link}. / This is a video call. We will send you the link.] Please bring [video call: Please have ready] the original ID documents you uploaded in Viventium Step 2 (for example, your photo ID). Questions? Call/text (417) 234-8494. Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 25,
  "name": "Office orientation (in-person backup) day-before reminder",
  "trigger": "Automatic: the Hub's hourly orientation reminder check (orientation-remind) looks at tomorrow's in-person office orientation sessions (the backup for someone who can't do it online; online new hires get the welcome call reminders) and texts everyone still booked. Practice (lists who it would remind, sends nothing) until it is switched on (Settings, Office orientation reminders, or the Owners Hub Admin page, Switches). When it goes on, the GoHighLevel workflow 'Orientation booked - remind' is turned off.",
  "automatic": true,
  "button": null,
  "timing": "The day before, from 10am Central (later that day if the 10am check could not run). Skipped if they booked the same day (the booking confirmation covers it).",
  "channel": "text only",
  "rule": "Once per person per session. Never to someone whose application said no to texts or who opted out; ends with \"Reply STOP to opt out.\" Who was reminded, skipped (and why) or not reached is listed in Settings, Office orientation reminders. A refused text raises a Needs Attention card; a check that cannot run raises one too.",
  "subject": null,
  "text": "Hi {first}, a reminder that your in-person Caring Companions orientation at our office is tomorrow, {Weekday, Month D} at {h:mm AM}. Location: 1331 N Stewart Ave Ste B, Springfield MO 65802. [an older video session says: your Caring Companions orientation video call ... This is a video call: {link}.] Please bring [video call: Please have ready] the original ID documents you uploaded in Viventium Step 2 (for example, your photo ID). Need to change it? Call or text us at (417) 234-8494. Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 27,
  "name": "Training invite (course assigned)",
  "trigger": "Admin assigns a course in the Training dashboard (training.mo-care.com); the dashboard calls send-invite. Stamps once only so the nightly welcome is skipped.",
  "automatic": false,
  "button": "Training dashboard → assign course",
  "timing": "Immediately when the office assigns the course. The text only goes 8am–6pm Central; the email any time.",
  "channel": "text + email",
  "rule": "Text 8am–6pm Central with \"Reply STOP to opt out.\"; after hours the email still goes and the office is told the text did not. Failures raise a card.",
  "subject": "Your training invitation: {course title}",
  "text": "Hi {first}, welcome to Caring Companions! You've been assigned your required training: {course} ({hours} hrs, due by {Month D}).\nStart any time on your phone. Your private link, no login needed:\nhttps://training.mo-care.com/#/me/{token}\nQuestions? Call or text the office: (417) 234-8494\nCaring Companions",
  "email_summary": "Welcome; course name + hours + due date; [Start my training]; works on any device, progress saves, completions recorded for your training file.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 28,
  "name": "Training reminder / sign-off reminder",
  "trigger": "Admin presses '✉ Send reminder' in the Training dashboard (any caregiver), OR the nightly sync when an In Training caregiver's course is due within 5 days (once per enrollment).",
  "automatic": true,
  "button": "Training dashboard → '✉ Send reminder' (manual path)",
  "timing": "Office button: immediately (text 8am–6pm only). Automatic: the daily run at about 9am Central.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central with \"Reply STOP to opt out.\"; automatic ones after hours are held and sent on the next run. Failures raise a card.",
  "subject": "Training reminder from Caring Companions  |  One quick step: sign off on your training",
  "text": "Hi {first}, a friendly reminder from Caring Companions: you still have required training to finish (due by {date}): {up to 3 course titles}.\nYour personal training link: https://training.mo-care.com/#/me/{token}\nQuestions? Call or text the office: (417) 234-8494\nCaring Companions   ||   Sign-off version: Hi {first}, one quick step from Caring Companions: please sign off on your completed training ({titles}). Open your personal link and tap Sign: {link} ...",
  "email_summary": "Reminder with [Continue my training], or sign-off version with [Sign off now] ('type your name to confirm you completed the training yourself').",
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 29,
  "name": "Course certificate email",
  "trigger": "Caregiver completes a course (their browser calls send-certificate with the PDF), or admin presses Certificate in the Training dashboard.",
  "automatic": true,
  "button": "Training dashboard → Certificate (admin path)",
  "timing": "Immediately on completion, any hour.",
  "channel": "email only",
  "rule": "Email only. A refused email raises a \"Didn't go through\" card.",
  "subject": "Your certificate: {course title}",
  "text": null,
  "email_summary": "'Congratulations! 🎉 You've completed {course} on {date}, and your official certificate is ready.' [Download my certificate] (1-year signed link).",
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 30,
  "name": "Cleared to work with clients",
  "trigger": "OLD PATH ONLY. Caregiver finishes the last pre-service course (browser calls notify-cleared), or the nightly sweep catches it. Also tries to flip AxisCare status to Active (left as it is; Samantha 2026-10-10). On the NEW onboarding path the Training Platform sends nothing: it reports the courses to the Hub's readiness card and the next entry applies.",
  "automatic": true,
  "button": null,
  "timing": "When they finish required training, 8am–6pm Central; finished at night, it goes with the next morning's run.",
  "channel": "text only",
  "rule": "Text with \"Reply STOP to opt out.\"; held (not lost) outside 8am–6pm. A refused text raises a card.",
  "subject": null,
  "text": "Hi {first}, now that you've completed your Alzheimer's & Dementia training, you are cleared to work with clients. Welcome to the team!\nFor anything you need, call or text the office, and save the number in your phone: (417) 234-8494.\nCaring Companions",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 30.5,
  "name": "Dementia course done, look out for open shifts (new path)",
  "trigger": "A person on the Approve to Work list presses Approve to Work on the readiness card AND AxisCare reads back Active (never before the read-back). Practice (recorded on the card, not sent) while the Admin switch \"Cleared text after Approve to Work\" is off.",
  "automatic": true,
  "button": "Readiness card → Approve to Work (Samantha or Zachary only)",
  "timing": "Right after the AxisCare read-back, 8am–6pm Central; after hours it is held and the readiness check (every ten minutes) sends it in hours.",
  "channel": "text only",
  "rule": "Text with \"Reply STOP to opt out.\"; their latest application's yes to texts; the opt-out door; a refused text raises a card and shows on the readiness card. Never says \"approved to work\" (her wording, 2026-10-10).",
  "subject": null,
  "text": "Hi {first}, we've been notified that you completed your Dementia course. Welcome to the team!\nKeep an eye out for our texts about open shifts, and check the Open Shifts section of the AxisCare app too.\nFor anything you need, call or text the office, and save the number in your phone: (417) 234-8494.\nCaring Companions",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "first shift",
  "order": 31,
  "name": "Availability link",
  "trigger": "Office presses the availability invite button; texts every active roster caregiver with nothing on file (or older than 90 days), never nurses, none invited in 30 days, 20 per press.",
  "automatic": false,
  "button": "Scheduling/Hours Watch → 'Text the availability link'",
  "timing": "Refused outside 10am–5pm Central.",
  "channel": "text only",
  "rule": "audience caregiver, opt-out check. Wording editable (ops_settings.coverage_msg_avail_invite).",
  "subject": null,
  "text": "Hi {first_name}, it's Caring Companions! Tell us the hours and days you WANT to work so we can offer you shifts first: cc.mo-care.com/availability It takes 30 seconds and you can update it anytime.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "first shift",
  "order": 32,
  "name": "Morning schedule text (shift-confirm)",
  "trigger": "Daily automatic check about 7am Central: each caregiver with visits today gets one list. Only when the switch is on in Settings.",
  "automatic": true,
  "button": null,
  "timing": "~6–7am Central on the day of the shift.",
  "channel": "text only",
  "rule": "Opt-out door. Wording editable (confirm_msg_head / confirm_msg_tail).",
  "subject": null,
  "text": "Good morning {first_name}! Here's your Caring Companions schedule for today:\n• {9:00a-1:00p} with {client}\nReply C to confirm. If anything's wrong, reply here or call the office at (417) 234-8494.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true,
  "warning": "Built but NOT switched on: the shift-confirm step is not running on the Hub, so this text is not being sent today."
 },
 {
  "stage": "first shift",
  "order": 33,
  "name": "How did your first shift go?",
  "trigger": "carematch-watch: a caregiver/client pair seen for the first time in AxisCare visits that have ended. Only when ops_settings.carematch_live is true.",
  "automatic": true,
  "button": null,
  "timing": "Morning after the shift (window reaches 3 days back).",
  "channel": "text only",
  "rule": "routine_internal. Opt-out door. One per pair ever.",
  "subject": null,
  "text": "Good morning, {first}! How did your first shift with {client first name} go?",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after first shift (PRN only)",
  "order": 34,
  "name": "PRN 60-day availability check-in",
  "trigger": "prn-reconfirm weekday job: PRN Team member whose availability was last confirmed 60+ days ago (or never). Practice mode until ops_settings.prn_reconfirm_live.",
  "automatic": true,
  "button": null,
  "timing": "Weekdays 10am–5pm Central; max 20/day; not twice in 14 days.",
  "channel": "text only",
  "rule": "Opt-out door. Wording editable (prn_reconfirm_msg). No second text; no reply after 14 days = call them.",
  "subject": null,
  "text": "Hi {first_name}! We're updating our Caring Companions PRN Team availability. Are you still available for the times you gave us? Tap to confirm or update: {link}",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "current caregivers (profile catch-up)",
  "order": 35,
  "name": "Caregiver profile link (current caregivers fill it in themselves)",
  "trigger": "The office presses Caregivers → '🪪 Profiles' → 'Send profile links to everyone who needs one' (or 'Send again to those waiting 3+ days'), sees who gets it and who can't be reached, confirms. One caregiver at a time: their page → '🪪 Caregiver profile' → 'Set up their link (they fill it in)' → 'Send profile link'.",
  "automatic": false,
  "button": "Caregivers → '🪪 Profiles' → 'Send profile links to everyone who needs one' / 'Send again to those waiting 3+ days'; or the employee's page → '🪪 Caregiver profile' → 'Send profile link'",
  "timing": "Immediately when pressed. Only caregivers already working with us (hired before 2026-10-02) who have no published profile; new hires keep the welcome-call photo link.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email always goes. Anything not sent is shown to the office and refused messages raise a Needs Attention card. On their page they answer three questions in their own words ('Help me say it' and 'Check my spelling' are there if they want them), add a photo AND a short video (both required for them), and tick the permission, which is required. The office checks and publishes.",
  "subject": "Your Caring Companions profile: 3 questions and a photo",
  "text": "Hi {first}, it's Caring Companions! We're adding a short profile that our families see before you visit, so they know who's coming. Please fill it in yourself here: https://cc.mo-care.com/caregiver-profile.html?t=.. Answer 3 short questions in your own words, and add a friendly photo (and a short hello video if you like). It takes about 10 minutes. Reply STOP to opt out.",
  "email_summary": "We're adding a short profile families see before you visit; please fill yours in yourself, about 10 minutes: 1. answer 3 short questions in your own words, 2. a friendly photo (a phone selfie in good light, shoulders up), 3. if they like, a short hello video of about 30 seconds (optional); 'Fill in my profile' button; the link is just for you; office phone.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "current caregivers (profile catch-up)",
  "order": 36,
  "name": "The hello video is now optional (one notice to every current caregiver)",
  "trigger": "The office presses Caregivers → '🪪 Profiles' → '📣 Tell everyone the video is optional', reads the text, sees who gets it, confirms. 2026-10-08, Samantha: the video on the caregiver profile is optional, tell all caregivers.",
  "automatic": false,
  "button": "Caregivers → '🪪 Profiles' → '📣 Tell everyone the video is optional'",
  "timing": "Immediately when pressed. Every current caregiver (active in AxisCare) with a mobile or email. Once per person, ever: anyone already told is skipped.",
  "channel": "text + email",
  "rule": "Texts 8am–6pm Central only, never to someone whose application said no to texts, and they end with \"Reply STOP to opt out.\" The email goes either way. Anything not sent is listed for the office, and a refused message raises a Needs Attention card.",
  "subject": "Your caregiver profile: the hello video is now optional",
  "text": "Hi {first}, it's Caring Companions! A quick update on your caregiver profile: the short hello video is now optional. A friendly photo is all we need, so if you would rather not be on camera, just skip the video. If you still need to finish your profile, use the link we sent you, or call or text the office at (417) 234-8494 and we will send a new one. Thank you! Reply STOP to opt out.",
  "email_summary": "A quick update on your caregiver profile: the short hello video is now optional. A friendly photo is all we need, so if you would rather not be on camera, just skip the video. If you still need to finish your profile, use the link we texted and emailed you; if you cannot find it, call or text the office and we will send a new one. Thank you!",
  "shows_in_ghl": true,
  "failure_visible": true
 }
];
window.AP_JOURNEY_ISSUES = [];
