/* Applicant journey & messages (2026-10-01, Samantha: "I need the full applicant experience to be mapped out with what
   messages they receive and attached somewhere in the hub pages so that our office admin know"). Built from the code as
   of 2026-10-01: every message an applicant / new hire gets, its exact wording, when it goes, what triggers it, and
   whether it shows in GoHighLevel Conversations. If a message is changed, update this list too. */
window.AP_JOURNEY_CHECKED = 'October 1, 2026';
window.AP_JOURNEY = [
 {
  "stage": "applying",
  "order": 1,
  "name": "Send the application (office, after a phone call)",
  "trigger": "Staff type name/phone/email/position in Applicants and press Send.",
  "automatic": false,
  "button": "Applicants → '📨 Send the application' → Send",
  "timing": "Immediately; refused outside 8am–6pm Central (any day). Same phone/email not sent twice in 24h.",
  "channel": "text + email",
  "rule": "Text only if staff ticked 'They asked us to text it'; email whenever there is an address. Opt-out door on both. 'Reply STOP to opt out.' appended. Wording editable in Settings (ops_settings.applicant_invite_msg). FAILURE: GoHighLevel refusal is shown only in the Send pop-up (raw fetch, no Needs Attention card); opt-out holds raise a card.",
  "subject": "Your application for {position} at Caring Companions",
  "text": "Hi {first_name}, thanks for calling Caring Companions! Here's the application for {position}. It takes about 2 minutes: {link} Reply STOP to opt out.",
  "email_summary": "Hi {first}, thanks for calling about our {position} position. Here is the application. It takes about 2 minutes, and at the end you can pick an interview time. [Start the application] Questions? Call us at {office phone}.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 2,
  "name": "Applied, not booked: nudge 1 (regular roles)",
  "trigger": "the interview messages job automatic check (every 15 min) finds an application (status partial/new, under 14 days old, not declined) with no booked interview.",
  "automatic": true,
  "button": null,
  "timing": "2 hours after applying; only 8am–6pm Central (held until 8am otherwise).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts (their yes to texts); email to anyone with an address. Opt-out door per channel. No STOP wording in the text.",
  "subject": "Pick a time to come and meet us",
  "text": "Hi {first}, thanks for applying to Caring Companions. You are one step from an interview, and you can pick a time that suits you here: https://mo-care.com/apply?book={applicant_id}",
  "email_summary": "Same words as the text with the link clickable, plus the 'Where to come' block (office name, address, map link, note, entrance photo).",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 3,
  "name": "Applied, not booked: nudge 1 (PRN CNA Team)",
  "trigger": "Same automatic check; PRN-track roles only, and only when the application cleared the screen (screen_grade 'qualified'). PRN applications that need a look get nothing automatically.",
  "automatic": true,
  "button": null,
  "timing": "10 minutes after they finish the application; 8am–6pm Central.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Choose your interview time: PRN CNA Team",
  "text": "Hi {first}! Thanks for applying for Caring Companions' PRN CNA Team. Based on your Priority Application, we'd like to meet you. Choose an interview time here: https://mo-care.com/apply?book={applicant_id}",
  "email_summary": "Same words as the text plus the 'Where to come' block.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 4,
  "name": "Applied, not booked: nudge 2",
  "trigger": "Same automatic check; still no booking.",
  "automatic": true,
  "button": null,
  "timing": "48 hours after applying; 8am–6pm Central.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Pick a time to come and meet us",
  "text": "Hi {first}, we still have interview times open this week if you would like one: https://mo-care.com/apply?book={applicant_id} Or call us on {office phone} and we will book it with you.",
  "email_summary": "Same words as the text (no address block).",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "applying",
  "order": 5,
  "name": "Applied, not booked: nudge 3 (last)",
  "trigger": "Same automatic check; still no booking.",
  "automatic": true,
  "button": null,
  "timing": "120 hours (5 days) after applying; 8am–6pm Central. At 7 days they are marked gave_up (no message).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "One last note from Caring Companions",
  "text": "Hi {first}, last note from us so we are not a nuisance. If you would still like to talk about caregiving work, pick a time here: https://mo-care.com/apply?book={applicant_id} or call {office phone}. We would be glad to hear from you.",
  "email_summary": "Same words as the text.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview booking",
  "order": 6,
  "name": "Interview booking confirmation",
  "trigger": "the interview messages job automatic check finds a booked interview with no a confirmation (booked on mo-care.com/apply, or by the office).",
  "automatic": true,
  "button": null,
  "timing": "Next 15-minute run after booking, 8am–6pm Central only (a 9pm booking is confirmed after 8am next day). If booked within 30h of the interview this also counts as the day-before reminder.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. No STOP wording.",
  "subject": "Your interview: {day} at {time}",
  "text": "Hi {first}, your interview with Caring Companions is booked for {Weekday, Month D} at {h:mm AM}, at {location line1, line2}. {location note} Need to move or cancel it? https://mo-care.com/apply?book={applicant_id} — or call {office phone}.",
  "email_summary": "'Your interview is booked for {day} at {time}.' + Where to come block (name, address, map, note, photo) + 'It takes about 30 minutes. Need to move or cancel it? You can do that here in a few taps, or call or text us on {phone}.' + 'We are looking forward to meeting you.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview booking",
  "order": 7,
  "name": "Interview cancelled notice",
  "trigger": "A booking is cancelled (by the applicant on their manage link, or by the office) and they have not already rebooked.",
  "automatic": true,
  "button": null,
  "timing": "Next 15-minute run, 8am–6pm Central; looks back 7 days.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. A cancel followed by a rebook before the run sends nothing (the new confirmation covers it).",
  "subject": "Your interview on {day} is cancelled",
  "text": "Hi {first}, your interview with Caring Companions for {day} at {time} is cancelled — nothing more to do. Want a different time? Pick one here: https://mo-care.com/apply?book={applicant_id} or call {office phone}.",
  "email_summary": "'Your interview for {day} at {time} is cancelled, nothing more to do on your side. If you would like a different time, pick one here whenever suits you, or call us on {phone}.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview reminders",
  "order": 8,
  "name": "Day-before reminder",
  "trigger": "the interview messages job automatic check: confirmed booking, not yet reminded, 2 to 30 hours away.",
  "automatic": true,
  "button": null,
  "timing": "Window opens 30h before; first run 8am–6pm Central inside that window. Skipped when the confirmation itself went inside 30h.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address.",
  "subject": "Tomorrow: your interview at {time}",
  "text": "Hi {first}, reminder: your interview is {day} at {time}, at {location}. {note} Need to move or cancel it? https://mo-care.com/apply?book={applicant_id} — or call {office phone}.",
  "email_summary": "'A reminder that your interview is tomorrow, {day} at {time}.' + Where to come block + 'It takes about 30 minutes...' + move/cancel link.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "interview reminders",
  "order": 9,
  "name": "Hour-before reminder",
  "trigger": "the interview messages job automatic check: 1.5 hours before to 15 minutes after the start, not yet sent.",
  "automatic": true,
  "button": null,
  "timing": "Up to 90 minutes before; 8am–6pm Central (so an 8am interview gets it at 8:00).",
  "channel": "text only",
  "rule": "Text only with their yes to texts. Email-only applicants get NO hour-before reminder.",
  "subject": null,
  "text": "Hi {first}, your interview with Caring Companions is at {time} today. We are at {location}. {note} See you shortly!",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "no-show",
  "order": 10,
  "name": "No-show message",
  "trigger": "Office presses 'Did not show' on the interview card (marks status noshow, closes the booking), or 'Send the no-show message' on the profile if it was held.",
  "automatic": false,
  "button": "Applicant interview card → 'Did not show'; profile → 'Send the no-show message' (only if not yet sent)",
  "timing": "Immediately, 8am–6pm Central (reactive). Outside hours the no-show is marked and the message waits for the profile button. Sent once (once only).",
  "channel": "text + email",
  "rule": "Text only with their yes to texts; email to anyone with an address. Opt-out door. Her wording, fixed in code.",
  "subject": "Missed Interview – Caring Companions",
  "text": "Hi {first}, this is Caring Companions In-Home Senior Care. You were scheduled for an in-person interview with our office today and did not attend or contact us prior to your scheduled interview time.\n\nYour application has been marked as a No-Show, which means you will not be eligible to reapply or be considered for employment with Caring Companions in the future.\n\nWe understand that unexpected circumstances can happen. If there is a reasonable explanation for missing your interview, please call our office at 417-234-8494 as soon as possible so we can discuss the situation.\n\nThank you,\nCaring Companions In-Home Senior Care\n\nReply STOP to opt out.",
  "email_summary": "Same substance: marked as a No-Show, not eligible to reapply or be considered for future employment; if there is a reasonable explanation call 417-234-8494 and we will discuss whether the application may be reconsidered.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "no-show",
  "order": 11,
  "name": "Excuse no-show & rebook (no message)",
  "trigger": "Office presses '✅ Excuse no-show & rebook' after the applicant calls; reason required. Status goes back to 'reviewing'.",
  "automatic": false,
  "button": "Applicant profile → '✅ Excuse no-show & rebook'",
  "timing": "n/a",
  "channel": "none",
  "rule": "Sends nothing. The office books the new time; the normal booking confirmation then goes out from the interview messages job.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 12,
  "name": "Start link (sent with the job offer)",
  "trigger": "Office fills the Offer a job form after 'Hire, make the offer' and presses 'Save offer & send their start link'.",
  "automatic": false,
  "button": "Applicant interview card → '✅ Hire — make the offer' → 'Save offer & send their start link'",
  "timing": "Immediately, any hour (no hours gate).",
  "channel": "text + email",
  "rule": "No their yes to texts check (the offer has no consent field); goes through the Hub opt-out check (the opt-out check). No STOP wording. Link carries their name, phone and email in the URL query string.",
  "subject": "Getting you started at Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to bring you onto the team. One quick step before your offer letter goes out: https://cc.mo-care.com/start.html?first=..&last=..&phone=..&email=.. It takes about two minutes and lets us start your reference checks today.",
  "email_summary": "'We would love to bring you onto the team. Your official offer letter and new-hire paperwork are on their way... Reference checks are the slowest part of hiring, so we start them the same day. This takes about two minutes: [Get started]' + office number.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 13,
  "name": "Start link resend (from staff's own phone/email)",
  "trigger": "Office presses 'Start link' on the hiring pipeline person row, then '💬 Text it' or '✉️ Email it'.",
  "automatic": false,
  "button": "Hiring pipeline row → 'Start link' → '💬 Text it' / '✉️ Email it' / '📋 Copy link'",
  "timing": "Whenever pressed.",
  "channel": "text or email from the staff member's own device",
  "rule": "Opens sms:/mailto: on the staff member's phone or computer. No opt-out check, no record.",
  "subject": "Getting you started at Caring Companions",
  "text": "Hi {first}, it's Caring Companions! We would love to bring you onto the team. One quick step before your offer letter goes out: {start link} It takes about two minutes and lets us start your reference checks today.",
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 14,
  "name": "Candidate pool / Not hiring (no message)",
  "trigger": "Office presses '🗂 Candidate pool' or 'Not hiring' on the interview card.",
  "automatic": false,
  "button": "Applicant interview card → '🗂 Candidate pool' / 'Not hiring'",
  "timing": "n/a",
  "channel": "none",
  "rule": "Nothing is sent. The Not hiring reason is 'kept for our records, never sent'. Applicant hears nothing.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 15,
  "name": "Not moving forward courtesy text (legacy Onboarding board)",
  "trigger": "Office presses 🚫 on an Onboarding board candidate, picks a reason (not 'withdrew'), then OKs the courtesy-text prompt.",
  "automatic": false,
  "button": "Onboarding board → 🚫 (Not moving forward) → confirm 'Send a courtesy text'",
  "timing": "Immediately, any hour.",
  "channel": "text only",
  "rule": "Staff door of send-candidate-message (staff wording). Opt-out door. No their yes to texts check, no hours gate, no STOP wording. Failure shown in an alert only.",
  "subject": null,
  "text": "Hi {first}, thank you for your interest in joining Caring Companions. After careful review, we won't be moving forward with your application at this time. We appreciate the time you invested and wish you all the best. — Caring Companions (417) 234-8494",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after interview (offer / pool / declined)",
  "order": 16,
  "name": "Tell past applicants about an opening",
  "trigger": "Office picks a group in 'Find someone for a case', writes the message, presses 'Send it'.",
  "automatic": false,
  "button": "Applicants → '🎯 Find someone for a case' → 'Send it'",
  "timing": "Weekdays 8am–6pm Central only (proactive). Nobody twice in 30 days.",
  "channel": "text + email",
  "rule": "Staff-written message. Text only with their yes to texts; email to anyone with an address. Skips declined/hired/offer and anyone with a booked interview. Does NOT skip no-shows.",
  "subject": "A new opening at Caring Companions",
  "text": "Hi {first}, {staff message} https://mo-care.com/apply?book={applicant_id} Reply STOP to hear no more from us.",
  "email_summary": "'Hi {first}, {staff message}' + [Pick an interview time] button + 'You applied with us before, which is why we thought of you. If you would rather we did not get in touch again, just reply and say so.'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 17,
  "name": "Reference nudge to the applicant",
  "trigger": "reference-chase (weekday automatic check + a poke when reference rows are created): a reference has been silent 5 days.",
  "automatic": true,
  "button": null,
  "timing": "5 days after the reference was first asked; weekdays 8am–6pm (automatic check 9:30/10:30am Central). Once per reference.",
  "channel": "text + email",
  "rule": "Text only with their yes to texts on the apply form (by applicant id, or every application with that number said yes). Opt-out door. 'Reply STOP to opt out.' included.",
  "subject": "We cannot reach {reference name}",
  "text": "Hi {first}, Caring Companions here. We have not been able to reach {reference name} for your reference, and it is the last thing holding up your start. Give them a nudge if you can. Or if you have a better number or email for them, or want to use someone else, do it here: https://cc.mo-care.com/fix-reference.html?r=..&cid=..&n=.. Reply STOP to opt out.",
  "email_summary": "'We have not been able to reach {ref} for your reference, and it is the last thing holding up your start with us. Could you give them a nudge? ... Or if you have a better number or email, or would rather use someone else, tell us here: [Give us a different contact]'",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 18,
  "name": "To the reference (not the applicant): first ask",
  "trigger": "reference-chase: a reference row with an email and no sent_at.",
  "automatic": true,
  "button": null,
  "timing": "As soon as the rows are created (Hub poke) or the next weekday 9:30am run; weekdays 8am–6pm.",
  "channel": "email only",
  "rule": "References are never texted automatically. No email = office call card.",
  "subject": "A quick reference for {candidate name}",
  "text": null,
  "email_summary": "'{candidate} listed you as a reference for a caregiving job with us... a few quick questions, no wrong answers. An honest middling answer helps us more than a glowing one.' [Answer a few quick questions]",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 19,
  "name": "To the reference (not the applicant): one reminder",
  "trigger": "reference-chase: reference silent 2 days.",
  "automatic": true,
  "button": null,
  "timing": "2 days after the first ask; weekdays 8am–6pm. Once.",
  "channel": "email only",
  "rule": "Email only.",
  "subject": "A quick reference for {candidate name}",
  "text": null,
  "email_summary": "'A gentle nudge. {candidate} is waiting on one reference before they can start, and yours is the last one we need.' [Answer a few quick questions]",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "references",
  "order": 20,
  "name": "To the reference (not the applicant): office sends the form",
  "trigger": "Office presses email or text on a reference in Background & References (text only after recording 'said OK to a text, by phone').",
  "automatic": false,
  "button": "Background & References → reference row → email the form / text the form",
  "timing": "Immediately, 8am–6pm Central.",
  "channel": "email or text",
  "rule": "Text needs recorded verbal OK. Raw fetch: a GoHighLevel refusal shows only to the person who pressed (no card).",
  "subject": "A quick reference for {candidate name}",
  "text": "Hi {ref first}, this is Caring Companions In-Home Senior Care. Thanks for saying we could text you. {candidate} listed you as a reference. A few quick questions, about two minutes: {link} Reply STOP to opt out.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "start paperwork",
  "order": 21,
  "name": "Welcome / what happens next (Viventium)",
  "trigger": "Office marks the offer 'entered in Viventium' (auto-sends), or presses '💬 Send welcome text + email' to retry.",
  "automatic": false,
  "button": "Hiring pipeline row → '☑ Viventium' / offer ladder 'Mark entered in Viventium'; retry '💬 Send welcome text + email'",
  "timing": "Immediately, any hour (no hours gate). Once (once only).",
  "channel": "text + email",
  "rule": "No their yes to texts check; Hub opt-out check per channel. No STOP wording. Failure: alert to staff if BOTH channels fail; a single failed channel is silent; no Needs Attention card.",
  "subject": "Welcome to Caring Companions — here’s what happens next",
  "text": "Hi {first}! Congratulations, and welcome to Caring Companions! 🎉\nWe're excited to begin the onboarding process with you.\n\nYour next step is to watch your email for a message from Viventium, our secure onboarding system. It will contain your official job offer and the first portion of your onboarding paperwork.\n\nPlease complete it as soon as possible. This paperwork gives us permission to begin your background check and contact your professional references.\n\nOnce your background check and references have been successfully completed, we'll contact you to schedule your paid new employee orientation.\n\n📞 Please save our office number: (417) 234-8494. This is our main office number and the one you'll use to call or text us if you have any questions.\n\nWelcome to the Caring Companions team!",
  "email_summary": "Congratulations + Step 1 complete Viventium paperwork (official offer + first paperwork; authorizes background check and references) / Step 2 background and reference checks / Step 3 we will contact you to schedule paid orientation / save office number (417) 234-8494.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "start paperwork",
  "order": 22,
  "name": "Viventium offer letter + paperwork reminders (external)",
  "trigger": "Office enters the hire in Viventium.",
  "automatic": true,
  "button": null,
  "timing": "Viventium's own schedule (code notes it reminds every 2 days).",
  "channel": "email (Viventium)",
  "rule": "Outside the Hub. Wording not in our code.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": false,
  "failure_visible": false,
  "ghl_note": "Does not appear in GoHighLevel Conversations."
 },
 {
  "stage": "orientation & training",
  "order": 23,
  "name": "Orientation invite (pick your date)",
  "trigger": "Office presses '📅 Invite' (or '📅 Re-send') on a candidate who is 'Ready for Orientation', reviews the text, confirms.",
  "automatic": false,
  "button": "Onboarding board (Ready for Orientation) → '📅 Invite' / '📅 Re-send'",
  "timing": "Immediately, any hour.",
  "channel": "text only",
  "rule": "Staff door of send-candidate-message. No their yes to texts check, no hours gate, no STOP wording. The link opens the booking page on sc.mo-care.com (fixed 2026-10-01; from the CC hub it used to give a 404). Failure: alert lets staff copy the link and mark Invited anyway; no card.",
  "subject": null,
  "text": "Hi {first}! Congratulations — you've been cleared to join Caring Companions! 🎉 Please choose your orientation date here: https://sc.mo-care.com/orientation-booking.html?sessions=..&first=..&last=..&phone=..&email=..&office=..&id=..\n\nQuestions? Call/text (417) 234-8494. We can't wait to meet you!",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 24,
  "name": "Orientation booking confirmation",
  "trigger": "Candidate picks a date on orientation-booking.html; the page asks send-candidate-message for the fixed confirmation (real booking in last 15 min, upcoming session).",
  "automatic": true,
  "button": null,
  "timing": "Instantly, any hour. One per phone per 24h.",
  "channel": "text only",
  "rule": "Opt-out door. No their yes to texts check, no hours gate, no STOP wording. Failure raises a Needs Attention card (reportSendProblem). Address hardcoded.",
  "subject": null,
  "text": "You're all set, {first}! 🎉 Your Caring Companions orientation is {Weekday, Month D, YYYY} at {h:mm AM}. Location: 1331 N Stewart Ave Ste B, Springfield MO 65802. [or: This is a video call: {link} / — we will send you the link.] Please bring your photo ID, Social Security card, and a voided check or bank info for direct deposit. Questions? Call/text (417) 234-8494.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 25,
  "name": "Orientation day-before reminder (GoHighLevel workflow)",
  "trigger": "orientation-booking.html calls orientation-booked, which posts to the GHL inbound webhook (GHL_HOOK_ORIENTATION), starting the GHL workflow 'Orientation booked - remind'.",
  "automatic": true,
  "button": null,
  "timing": "Day before orientation (reminder_date); exact time set in GHL.",
  "channel": "text (per code comment)",
  "rule": "Wording, timing and consent rules live in the GHL workflow, not in code. Webhook failure is only logged; the page ignores it.",
  "subject": null,
  "text": null,
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 26,
  "name": "Training welcome (nightly sync)",
  "trigger": "Training Platform nightly sync-axiscare: a caregiver now 'In Training' in AxisCare with a personal link and no once only.",
  "automatic": true,
  "button": null,
  "timing": "Nightly job (runs about 2–3am Central).",
  "channel": "text + email",
  "rule": "Only 'In Training' caregivers. opt-out check. No their yes to texts, no hours gate, no STOP wording. If it fails, nothing tells the office yet.",
  "subject": "Welcome to Caring Companions — your training is ready",
  "text": "Hi {first}, welcome to Caring Companions! Your required training is ready — start any time on your phone:\nhttps://training.mo-care.com/#/me/{token}\nThis private link is just for you (no login needed).\nQuestions? Call or text the office: (417) 234-8494\n— Caring Companions",
  "email_summary": "Welcome; training link [Start my training]; 'Before your first client visit, please complete Agency Orientation (2 hours) and Alzheimer's & Dementia Care (4 hours)'; 'When you finish, you'll get a message confirming you're cleared to work with clients.'",
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 27,
  "name": "Training invite (course assigned)",
  "trigger": "Admin assigns a course in the Training dashboard (training.mo-care.com); the dashboard calls send-invite. Stamps once only so the nightly welcome is skipped.",
  "automatic": false,
  "button": "Training dashboard → assign course",
  "timing": "Immediately, any hour.",
  "channel": "text + email",
  "rule": "Only 'In Training' (active staff skipped). Opt-out check. No their yes to texts, hours gate or STOP wording. Failure returned to dashboard only if both channels fail.",
  "subject": "Your training invitation — {course title}",
  "text": "Hi {first}, welcome to Caring Companions! You've been assigned your required training: {course} ({hours} hrs, due by {Month D}).\nStart any time on your phone — your private link, no login needed:\nhttps://training.mo-care.com/#/me/{token}\nQuestions? Call or text the office: (417) 234-8494\n— Caring Companions",
  "email_summary": "Welcome; course name + hours + due date; [Start my training]; works on any device, progress saves, completions recorded for your training file.",
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "orientation & training",
  "order": 28,
  "name": "Training reminder / sign-off reminder",
  "trigger": "Admin presses '✉ Send reminder' in the Training dashboard (any caregiver), OR the nightly sync when an In Training caregiver's course is due within 5 days (once per enrollment).",
  "automatic": true,
  "button": "Training dashboard → '✉ Send reminder' (manual path)",
  "timing": "Manual: immediately. Automatic: nightly job (about 2–3am Central), 5 days before due.",
  "channel": "text + email",
  "rule": "Opt-out check. No their yes to texts/hours/STOP. Sign-off version when all courses are done but not attested.",
  "subject": "Training reminder — Caring Companions  |  One quick step — sign off on your training",
  "text": "Hi {first}, a friendly reminder from Caring Companions — you still have required training to finish (due by {date}): {up to 3 course titles}.\nYour personal training link: https://training.mo-care.com/#/me/{token}\nQuestions? Call or text the office: (417) 234-8494\n— Caring Companions   ||   Sign-off version: Hi {first}, one quick step from Caring Companions — please sign off on your completed training ({titles}). Open your personal link and tap Sign: {link} ...",
  "email_summary": "Reminder with [Continue my training], or sign-off version with [Sign off now] ('type your name to confirm you completed the training yourself').",
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 29,
  "name": "Course certificate email",
  "trigger": "Caregiver completes a course (their browser calls send-certificate with the PDF), or admin presses Certificate in the Training dashboard.",
  "automatic": true,
  "button": "Training dashboard → Certificate (admin path)",
  "timing": "Immediately on completion, any hour.",
  "channel": "email only",
  "rule": "Opt-out check. Failure returned to the caller only.",
  "subject": "Your certificate — {course title}",
  "text": null,
  "email_summary": "'Congratulations! 🎉 You've completed {course} on {date}, and your official certificate is ready.' [Download my certificate] (1-year signed link).",
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "orientation & training",
  "order": 30,
  "name": "Cleared to work with clients",
  "trigger": "Caregiver finishes the last pre-service course (browser calls notify-cleared), or the nightly sweep catches it. Also flips AxisCare status to Active.",
  "automatic": true,
  "button": null,
  "timing": "Immediately on completion (any hour), or nightly 2–3am Central sweep. Once.",
  "channel": "text only",
  "rule": "Only 'In Training'. Opt-out check. No their yes to texts/hours/STOP. Failure not reported (retries nightly).",
  "subject": null,
  "text": "Hi {first}, now that you've completed your Alzheimer's & Dementia training, you are cleared to work with clients. Welcome to the team!\nFrom now on, use our office number for everything — save it in your phone: (417) 234-8494. This automated number isn't monitored day to day.\n— Caring Companions",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": false
 },
 {
  "stage": "first shift",
  "order": 31,
  "name": "Availability link",
  "trigger": "Office presses the availability invite button; texts every active roster caregiver with nothing on file (or older than 90 days), never nurses, none invited in 30 days, 20 per press.",
  "automatic": false,
  "button": "Scheduling/Hours Watch → 'Text the availability link'",
  "timing": "Refused outside 10am–5pm Central.",
  "channel": "text only",
  "rule": "audience caregiver, opt-out check. Wording editable (ops_settings.coverage_msg_avail_invite).",
  "subject": null,
  "text": "Hi {first_name}, it's Caring Companions! Tell us the hours and days you WANT to work so we can offer you shifts first: cc.mo-care.com/availability It takes 30 seconds and you can update it anytime.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "first shift",
  "order": 32,
  "name": "Morning schedule text (shift-confirm)",
  "trigger": "Daily automatic check about 7am Central: each caregiver with visits today gets one list. Only when the switch is on in Settings.",
  "automatic": true,
  "button": null,
  "timing": "~6–7am Central on the day of the shift.",
  "channel": "text only",
  "rule": "Opt-out door. Wording editable (confirm_msg_head / confirm_msg_tail).",
  "subject": null,
  "text": "Good morning {first_name}! Here's your Caring Companions schedule for today:\n• {9:00a-1:00p} with {client}\nReply C to confirm. If anything's wrong, reply here or call the office at (417) 234-8494.",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true,
  "warning": "Built but NOT switched on: the shift-confirm step is not running on the Hub, so this text is not being sent today."
 },
 {
  "stage": "first shift",
  "order": 33,
  "name": "How did your first shift go?",
  "trigger": "carematch-watch: a caregiver/client pair seen for the first time in AxisCare visits that have ended. Only when ops_settings.carematch_live is true.",
  "automatic": true,
  "button": null,
  "timing": "Morning after the shift (window reaches 3 days back).",
  "channel": "text only",
  "rule": "routine_internal. Opt-out door. One per pair ever.",
  "subject": null,
  "text": "Good morning, {first}! How did your first shift with {client first name} go?",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 },
 {
  "stage": "after first shift (PRN only)",
  "order": 34,
  "name": "PRN 60-day availability check-in",
  "trigger": "prn-reconfirm weekday job: PRN Team member whose availability was last confirmed 60+ days ago (or never). Practice mode until ops_settings.prn_reconfirm_live.",
  "automatic": true,
  "button": null,
  "timing": "Weekdays 10am–5pm Central; max 20/day; not twice in 14 days.",
  "channel": "text only",
  "rule": "Opt-out door. Wording editable (prn_reconfirm_msg). No second text; no reply after 14 days = call them.",
  "subject": null,
  "text": "Hi {first_name}! We're updating our Caring Companions PRN Team availability. Are you still available for the times you gave us? Tap to confirm or update: {link}",
  "email_summary": null,
  "shows_in_ghl": true,
  "failure_visible": true
 }
];
window.AP_JOURNEY_ISSUES = [
 "Job offer, orientation invite, the old \"not moving forward\" text and all Training Platform texts: no 8am–6pm limit, no \"Reply STOP\" line, and they do not check the applicant's yes to texts.",
 "Training welcome and training reminders are sent by a nightly job at about 2–3am Central (not yet checked against the live schedule).",
 "If a Training Platform message fails, nothing tells the office yet (no \"Didn't go through\" card).",
 "The start and orientation links carry the person's name, phone and email in the web address.",
 "Wording that does not match: the interview confirmation email says about 30 minutes, the apply page says 45; the apply page promises an hour-before reminder, which only goes by text.",
 "The welcome email lists 6 hours of training (Orientation 2 + Alzheimer's 4); the full basic training requirement is longer.",
 "\"Not hiring\" and \"Candidate pool\" send nothing to the applicant.",
 "The orientation day-before reminder lives in a GoHighLevel workflow: its wording and time are set in GoHighLevel, not here."
];
